export const COUNTRY_FACTS: Readonly<Record<string, string>> = {
  "AF": "It is landlocked in Southern Asia, has 6 land neighbors, and a large population.",
  "AL": "It sits in Southeast Europe, has 4 land neighbors, and a population below five million.",
  "DZ": "It sits in Northern Africa, has 7 land neighbors, and a large population.",
  "AD": "It is landlocked in Southern Europe, has 2 land neighbors, and under 100,000 residents.",
  "AO": "It sits in Middle Africa, has 4 land neighbors, and a large population.",
  "AG": "It has no land borders, a very small land footprint, and under one million residents.",
  "AR": "It sits in South America, has 5 land neighbors, and a large population.",
  "AM": "It is landlocked in Western Asia, has 4 land neighbors, and a population below five million.",
  "AU": "It has no land borders, a vast land area, and a large population.",
  "AT": "It is landlocked in Central Europe, has 8 land neighbors, and a mid-sized population.",
  "AZ": "It is landlocked in Western Asia, has 5 land neighbors, and a mid-sized population.",
  "BS": "It has no land borders, a compact land area, and under one million residents.",
  "BH": "It has no land borders, a very small land footprint, and a population below five million.",
  "BD": "It sits in Southern Asia, has 2 land neighbors, and one of the world’s larger populations.",
  "BB": "It has no land borders, a very small land footprint, and under one million residents.",
  "BY": "It is landlocked in Eastern Europe, has 5 land neighbors, and a mid-sized population.",
  "BE": "It sits in Western Europe, has 4 land neighbors, and a mid-sized population.",
  "BZ": "It sits in Central America, has 2 land neighbors, and under one million residents.",
  "BJ": "It sits in Western Africa, has 4 land neighbors, and a mid-sized population.",
  "BT": "It is landlocked in Southern Asia, has 2 land neighbors, and under one million residents.",
  "BO": "It is landlocked in South America, has 5 land neighbors, and a mid-sized population.",
  "BA": "It sits in Southeast Europe, has 3 land neighbors, and a population below five million.",
  "BW": "It is landlocked in Southern Africa, has 4 land neighbors, and a population below five million.",
  "BR": "It sits in South America, has 10 land neighbors, and one of the world’s larger populations.",
  "BN": "It sits in South-Eastern Asia, has 1 land neighbor, and under one million residents.",
  "BG": "It sits in Southeast Europe, has 5 land neighbors, and a mid-sized population.",
  "BF": "It is landlocked in Western Africa, has 6 land neighbors, and a large population.",
  "BI": "It is landlocked in Eastern Africa, has 3 land neighbors, and a mid-sized population.",
  "CV": "It has no land borders, a compact land area, and under one million residents.",
  "KH": "It sits in South-Eastern Asia, has 3 land neighbors, and a mid-sized population.",
  "CM": "It sits in Middle Africa, has 6 land neighbors, and a large population.",
  "CA": "It sits in North America, has 1 land neighbor, and a large population.",
  "CF": "It is landlocked in Middle Africa, has 6 land neighbors, and a mid-sized population.",
  "TD": "It is landlocked in Middle Africa, has 6 land neighbors, and a mid-sized population.",
  "CL": "It sits in South America, has 3 land neighbors, and a large population.",
  "CN": "It sits in Eastern Asia, has 16 land neighbors, and one of the world’s larger populations.",
  "CO": "It sits in South America, has 5 land neighbors, and a large population.",
  "KM": "It has no land borders, a compact land area, and under one million residents.",
  "CG": "It sits in Middle Africa, has 5 land neighbors, and a mid-sized population.",
  "CR": "It sits in Central America, has 2 land neighbors, and a mid-sized population.",
  "CI": "It sits in Western Africa, has 5 land neighbors, and a large population.",
  "HR": "It sits in Southeast Europe, has 5 land neighbors, and a population below five million.",
  "CU": "It has no land borders, a moderate land area, and a mid-sized population.",
  "CY": "It has no land borders, a compact land area, and a population below five million.",
  "CZ": "It is landlocked in Central Europe, has 4 land neighbors, and a mid-sized population.",
  "CD": "It sits in Middle Africa, has 9 land neighbors, and one of the world’s larger populations.",
  "DK": "It sits in Northern Europe, has 1 land neighbor, and a mid-sized population.",
  "DJ": "It sits in Eastern Africa, has 3 land neighbors, and a population below five million.",
  "DM": "It has no land borders, a very small land footprint, and under 100,000 residents.",
  "DO": "It sits in Caribbean, has 1 land neighbor, and a mid-sized population.",
  "EC": "It sits in South America, has 2 land neighbors, and a mid-sized population.",
  "EG": "It sits in Northern Africa, has 4 land neighbors, and one of the world’s larger populations.",
  "SV": "It sits in Central America, has 2 land neighbors, and a mid-sized population.",
  "GQ": "It sits in Middle Africa, has 2 land neighbors, and a population below five million.",
  "ER": "It sits in Eastern Africa, has 3 land neighbors, and a population below five million.",
  "EE": "It sits in Northern Europe, has 2 land neighbors, and a population below five million.",
  "SZ": "It is landlocked in Southern Africa, has 2 land neighbors, and a population below five million.",
  "ET": "It is landlocked in Eastern Africa, has 6 land neighbors, and one of the world’s larger populations.",
  "FJ": "It has no land borders, a compact land area, and under one million residents.",
  "FI": "It sits in Northern Europe, has 3 land neighbors, and a mid-sized population.",
  "FR": "It sits in Western Europe, has 8 land neighbors, and a large population.",
  "GA": "It sits in Middle Africa, has 3 land neighbors, and a population below five million.",
  "GM": "It sits in Western Africa, has 1 land neighbor, and a population below five million.",
  "GE": "It sits in Western Asia, has 4 land neighbors, and a population below five million.",
  "DE": "It sits in Western Europe, has 9 land neighbors, and one of the world’s larger populations.",
  "GH": "It sits in Western Africa, has 3 land neighbors, and a large population.",
  "GR": "It sits in Southern Europe, has 4 land neighbors, and a mid-sized population.",
  "GD": "It has no land borders, a very small land footprint, and under one million residents.",
  "GT": "It sits in Central America, has 4 land neighbors, and a mid-sized population.",
  "GN": "It sits in Western Africa, has 6 land neighbors, and a mid-sized population.",
  "GW": "It sits in Western Africa, has 2 land neighbors, and a population below five million.",
  "GY": "It sits in South America, has 3 land neighbors, and under one million residents.",
  "HT": "It sits in Caribbean, has 1 land neighbor, and a mid-sized population.",
  "HN": "It sits in Central America, has 3 land neighbors, and a mid-sized population.",
  "HU": "It is landlocked in Central Europe, has 7 land neighbors, and a mid-sized population.",
  "IS": "It has no land borders, a moderate land area, and under one million residents.",
  "IN": "It sits in Southern Asia, has 6 land neighbors, and one of the world’s larger populations.",
  "ID": "It sits in South-Eastern Asia, has 3 land neighbors, and one of the world’s larger populations.",
  "IR": "It sits in Southern Asia, has 7 land neighbors, and one of the world’s larger populations.",
  "IQ": "It sits in Western Asia, has 6 land neighbors, and a large population.",
  "IE": "It sits in Northern Europe, has 1 land neighbor, and a mid-sized population.",
  "IL": "It sits in Western Asia, has 5 land neighbors, and a mid-sized population.",
  "IT": "It sits in Southern Europe, has 6 land neighbors, and a large population.",
  "JM": "It has no land borders, a compact land area, and a population below five million.",
  "JP": "It has no land borders, a large land area, and one of the world’s larger populations.",
  "JO": "It sits in Western Asia, has 5 land neighbors, and a mid-sized population.",
  "KZ": "It is landlocked in Central Asia, has 5 land neighbors, and a large population.",
  "KE": "It sits in Eastern Africa, has 5 land neighbors, and a large population.",
  "KI": "It has no land borders, a very small land footprint, and under one million residents.",
  "KW": "It sits in Western Asia, has 2 land neighbors, and a population below five million.",
  "KG": "It is landlocked in Central Asia, has 4 land neighbors, and a mid-sized population.",
  "LA": "It is landlocked in South-Eastern Asia, has 5 land neighbors, and a mid-sized population.",
  "LV": "It sits in Northern Europe, has 4 land neighbors, and a population below five million.",
  "LB": "It sits in Western Asia, has 2 land neighbors, and a mid-sized population.",
  "LS": "It is landlocked in Southern Africa, has 1 land neighbor, and a population below five million.",
  "LR": "It sits in Western Africa, has 3 land neighbors, and a mid-sized population.",
  "LY": "It sits in Northern Africa, has 6 land neighbors, and a mid-sized population.",
  "LI": "It is landlocked in Western Europe, has 2 land neighbors, and under 100,000 residents.",
  "LT": "It sits in Northern Europe, has 4 land neighbors, and a population below five million.",
  "LU": "It is landlocked in Western Europe, has 3 land neighbors, and under one million residents.",
  "MG": "It has no land borders, a large land area, and a large population.",
  "MW": "It is landlocked in Eastern Africa, has 3 land neighbors, and a large population.",
  "MY": "It sits in South-Eastern Asia, has 3 land neighbors, and a large population.",
  "MV": "It has no land borders, a very small land footprint, and under one million residents.",
  "ML": "It is landlocked in Western Africa, has 7 land neighbors, and a large population.",
  "MT": "It has no land borders, a very small land footprint, and under one million residents.",
  "MH": "It has no land borders, a very small land footprint, and under 100,000 residents.",
  "MR": "It sits in Western Africa, has 4 land neighbors, and a population below five million.",
  "MU": "It has no land borders, a compact land area, and a population below five million.",
  "MX": "It sits in North America, has 3 land neighbors, and one of the world’s larger populations.",
  "FM": "It has no land borders, a very small land footprint, and under one million residents.",
  "MD": "It is landlocked in Eastern Europe, has 2 land neighbors, and a population below five million.",
  "MC": "It sits in Western Europe, has 1 land neighbor, and under 100,000 residents.",
  "MN": "It is landlocked in Eastern Asia, has 2 land neighbors, and a population below five million.",
  "ME": "It sits in Southeast Europe, has 5 land neighbors, and under one million residents.",
  "MA": "It sits in Northern Africa, has 3 land neighbors, and a large population.",
  "MZ": "It sits in Eastern Africa, has 6 land neighbors, and a large population.",
  "MM": "It sits in South-Eastern Asia, has 5 land neighbors, and a large population.",
  "NA": "It sits in Southern Africa, has 4 land neighbors, and a population below five million.",
  "NR": "It has no land borders, a very small land footprint, and under 100,000 residents.",
  "NP": "It is landlocked in Southern Asia, has 2 land neighbors, and a large population.",
  "NL": "It sits in Western Europe, has 2 land neighbors, and a mid-sized population.",
  "NZ": "It has no land borders, a large land area, and a mid-sized population.",
  "NI": "It sits in Central America, has 2 land neighbors, and a mid-sized population.",
  "NE": "It is landlocked in Western Africa, has 7 land neighbors, and a large population.",
  "NG": "It sits in Western Africa, has 4 land neighbors, and one of the world’s larger populations.",
  "KP": "It sits in Eastern Asia, has 3 land neighbors, and a large population.",
  "MK": "It is landlocked in Southeast Europe, has 5 land neighbors, and a population below five million.",
  "NO": "It sits in Northern Europe, has 3 land neighbors, and a mid-sized population.",
  "OM": "It sits in Western Asia, has 3 land neighbors, and a mid-sized population.",
  "PK": "It sits in Southern Asia, has 4 land neighbors, and one of the world’s larger populations.",
  "PW": "It has no land borders, a very small land footprint, and under 100,000 residents.",
  "PA": "It sits in Central America, has 2 land neighbors, and a population below five million.",
  "PG": "It sits in Melanesia, has 1 land neighbor, and a mid-sized population.",
  "PY": "It is landlocked in South America, has 3 land neighbors, and a mid-sized population.",
  "PE": "It sits in South America, has 5 land neighbors, and a large population.",
  "PH": "It has no land borders, a large land area, and one of the world’s larger populations.",
  "PL": "It sits in Central Europe, has 7 land neighbors, and a large population.",
  "PT": "It sits in Southern Europe, has 1 land neighbor, and a mid-sized population.",
  "QA": "It sits in Western Asia, has 1 land neighbor, and a population below five million.",
  "RO": "It sits in Southeast Europe, has 5 land neighbors, and a mid-sized population.",
  "RU": "It sits in Eastern Europe, has 14 land neighbors, and one of the world’s larger populations.",
  "RW": "It is landlocked in Eastern Africa, has 4 land neighbors, and a mid-sized population.",
  "KN": "It has no land borders, a very small land footprint, and under 100,000 residents.",
  "LC": "It has no land borders, a very small land footprint, and under one million residents.",
  "VC": "It has no land borders, a very small land footprint, and under one million residents.",
  "WS": "It has no land borders, a compact land area, and under one million residents.",
  "SM": "It is landlocked in Southern Europe, has 1 land neighbor, and under 100,000 residents.",
  "ST": "It has no land borders, a very small land footprint, and under one million residents.",
  "SA": "It sits in Western Asia, has 7 land neighbors, and a large population.",
  "SN": "It sits in Western Africa, has 5 land neighbors, and a mid-sized population.",
  "RS": "It is landlocked in Southeast Europe, has 8 land neighbors, and a mid-sized population.",
  "SC": "It has no land borders, a very small land footprint, and under one million residents.",
  "SL": "It sits in Western Africa, has 2 land neighbors, and a mid-sized population.",
  "SG": "It has no land borders, a very small land footprint, and a mid-sized population.",
  "SK": "It is landlocked in Central Europe, has 5 land neighbors, and a mid-sized population.",
  "SI": "It sits in Central Europe, has 4 land neighbors, and a population below five million.",
  "SB": "It has no land borders, a moderate land area, and under one million residents.",
  "SO": "It sits in Eastern Africa, has 3 land neighbors, and a mid-sized population.",
  "ZA": "It sits in Southern Africa, has 6 land neighbors, and a large population.",
  "KR": "It sits in Eastern Asia, has 1 land neighbor, and a large population.",
  "SS": "It is landlocked in Middle Africa, has 6 land neighbors, and a mid-sized population.",
  "ES": "It sits in Southern Europe, has 5 land neighbors, and a large population.",
  "LK": "It has no land borders, a moderate land area, and a large population.",
  "SD": "It sits in Northern Africa, has 7 land neighbors, and a large population.",
  "SR": "It sits in South America, has 3 land neighbors, and under one million residents.",
  "SE": "It sits in Northern Europe, has 2 land neighbors, and a mid-sized population.",
  "CH": "It is landlocked in Western Europe, has 5 land neighbors, and a mid-sized population.",
  "SY": "It sits in Western Asia, has 5 land neighbors, and a large population.",
  "TJ": "It is landlocked in Central Asia, has 4 land neighbors, and a mid-sized population.",
  "TZ": "It sits in Eastern Africa, has 8 land neighbors, and a large population.",
  "TH": "It sits in South-Eastern Asia, has 4 land neighbors, and a large population.",
  "TL": "It sits in South-Eastern Asia, has 1 land neighbor, and a population below five million.",
  "TG": "It sits in Western Africa, has 3 land neighbors, and a mid-sized population.",
  "TO": "It has no land borders, a very small land footprint, and under one million residents.",
  "TT": "It has no land borders, a compact land area, and a population below five million.",
  "TN": "It sits in Northern Africa, has 2 land neighbors, and a mid-sized population.",
  "TR": "It sits in Western Asia, has 8 land neighbors, and one of the world’s larger populations.",
  "TM": "It is landlocked in Central Asia, has 4 land neighbors, and a mid-sized population.",
  "TV": "It has no land borders, a very small land footprint, and under 100,000 residents.",
  "UG": "It is landlocked in Eastern Africa, has 5 land neighbors, and a large population.",
  "UA": "It sits in Eastern Europe, has 7 land neighbors, and a large population.",
  "AE": "It sits in Western Asia, has 2 land neighbors, and a mid-sized population.",
  "GB": "It sits in Northern Europe, has 1 land neighbor, and a large population.",
  "US": "It sits in North America, has 2 land neighbors, and one of the world’s larger populations.",
  "UY": "It sits in South America, has 2 land neighbors, and a population below five million.",
  "UZ": "It is landlocked in Central Asia, has 5 land neighbors, and a large population.",
  "VU": "It has no land borders, a compact land area, and under one million residents.",
  "VE": "It sits in South America, has 3 land neighbors, and a large population.",
  "VN": "It sits in South-Eastern Asia, has 3 land neighbors, and one of the world’s larger populations.",
  "YE": "It sits in Western Asia, has 2 land neighbors, and a large population.",
  "ZM": "It is landlocked in Eastern Africa, has 8 land neighbors, and a mid-sized population.",
  "ZW": "It is landlocked in Southern Africa, has 4 land neighbors, and a mid-sized population.",
  "VA": "It is landlocked in Southern Europe, has 1 land neighbor, and under 100,000 residents.",
  "PS": "It sits in Western Asia, has 3 land neighbors, and a mid-sized population.",
  "TW": "It has no land borders, a moderate land area, and a large population."
};
